behaviors:
    TreeBuilder:
        trainer_type: ppo

        max_steps: 10
        time_horizon: 5
        summary_freq: 5

        hyperparameters:
            batch_size: 5
            buffer_size: 10

            learning_rate: 0.0003

            beta: 0.01
            epsilon: 0.25
            lambd: 0.945

            num_epoch: 15
            learning_rate_schedule: linear

        network_settings:
            hidden_units: 128
            num_layers: 4

        reward_signals:
            extrinsic:
                gamma: 0.995
                strength: 1.0